### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by ErrorPro** [facebook/dataloader#27] opened 2016-06-13 12:59 UTC
Hello. I have a dataloader in my application which fetches a current user's profile. I am passing 'me' as a key and i want my dataloader to return same Promise for all it's load function.

```
   UserProfile: new DataLoader(async (keys) => {
      return Promise.all(keys.map(async () => {
          ..fetch and return data. hit /api/user enpoint
      }));
   });
```

So it's working, but the loader still sends two request to my API server. I found that when load function gets invoke in the first two times this._promiseCache.entries() returns empty object and only in the third time it returns `MapIterator { [ 'me', Promise { _d: [Object] } ] }`. And i also tried to add the key to my custom object in the beginning of the load function and print it every time the load function gets invoked. And it worked perfect, first time it was undefined but the next invokations it was defined. Is there any way to fix it? Do i something wrong?

**Comment by ryancole** [comment] 2016-07-16 03:43
Is it because you're using `async` perhaps, with a lib that naturally handles `Promise`?

**Comment by ErrorPro** [comment] 2016-07-28 10:08
Yes i am using Promise.all! And yes, you are right. But do you see any other ways to handle it? I have an array of IDs, and i need to return a promise for each of IDs.

**Comment by idris** [comment] 2016-08-01 17:01
@ErrorPro try removing the `async` on the first line.  You don't need it because you're returning `Promise.all` which is already a promise.

**Comment by ErrorPro** [comment] 2016-08-02 14:29
@idris the thing is that i am using Promise.all(promises). It supposed to run all promises async(runs each of promises at the same time). So removing async didn't help me.

**Comment by leebyron** [comment] 2016-08-16 00:05
Could you reduce this to some minimal code that we could run to attempt to reproduce the issue? If there is a race condition than I'd like to include a test to prove it so we can fix it. However right now I'm having trouble recreating the issue you're describing.

**Comment by leebyron** [comment] 2016-09-23 20:28
Closing this issue since it's aging.

If you end up finding an issue where you have some code that could be easily run by someone else that illustrates the problem, then that would help identify a test case to work around.

However my hunch is probably that your usage is incorrect based on mixing async functions with Promises in ways that the language does not expect.

**Closed by leebyron** 2016-09-23 20:28 UTC
