### ISSUE TITLE
Talking of Dataloader as a Cache confuses developers

### ISSUE THREAD

**Issue by ThisIsMissEm** [facebook/dataloader#62] opened 2016-12-06 18:52 UTC
Hi, I'll keep this fairly brief for now, but try to expand it later.

A common issue I've seen with people using Dataloader is that they either use it as an application-wide cache, or they don't understand how dataloader works at a lower-level, and misunderstand why they are using it.

I feel like this is mainly a documentation issue. Dataloader is a data loading mechanism, where you load that data from is arbitrary, all that Dataloader ensures is that a signal value by a given key always resolves to the same value.

That is, I've seen people create a dataloader instance at application level, and think that this is safe because they're calling `userLoader.clear()` after changing a user. The problem with this is that that `userLoader.clear()` isn't broadcast to all other instances in your cluster.

Say you have a node.js server using dataloader, and you horizontally scale it — if you retain data between requests than you can get a case where `server1`'s dataloader has a different local state to `server2` which could have a different state from the database (e.g., `server3` has written to the database) — this issue is encountered as soon as you go from one process to more than one process, because the dataloader "cache" is in-process-memory, not some sort of shared memory for all processes. (e.g., using memcached for caching would be sharing that memory between servers / processes)

I think there's a better way to communicate what dataloader is doing, and it should be highly promoted that dataloader is best suited to per-request caching (such that all values by a given key resolve to the same value within the one request, such that you don't get data-drift within the one request — sort of a snapshot of the world at that given time).

if the storage for the "cached" state for dataloader actually came from a shared datasource (memcached, redis, etc), then this issue would be avoided completely; but then you're also by-passing the point of dataloader in some ways.

I'd be willing to restructure / rewrite the documentation to be clearer as to split the "what it does" from the "api for doing it" – then again, I'd be fairly inclined to say `clear` or `reset` are anti-patterns, and shouldn't be generally used — i.e., don't use them to clear state between requests, only between the instance of that object in one request, e.g.,

```
1 request start
2  -> userLoader.get(1)
3    -> Users.update(1, { new: "data" })
4       -> userLoader.clear(1);
5          respond with userLoader.get(1)
6          -> request end
```

i.e., that second userLoader.get call shouldn't return the result from line 2, instead, it should return the fresh result from the database.

Perhaps a better API would be `userLoader.get()` and `userLoader.getFresh()` — i.e., we're not talking about a cache, as it's not a "cache" but more a call identity memoization.

I'd be interested in hearing others thoughts here, in particular, let me know if this makes any sense at all, and whether you'd be interested in a PR to redocument this project to help users avoid misunderstandings

**Comment by luckydrq** [comment] 2016-12-11 06:52
I was considering a single dataloader instance at app level, and wanted to use IPC to sync data between worker processes. But i haven't considered about the case when there are multiple servers. So yes, now i have got a clear decision on this. Thank you!

**Comment by rturk** [comment] 2017-01-14 17:52
@ThisIsMissEm this is good point, needs to be better documented

That is, I've seen people create a dataloader instance at application level, and think that this is safe because they're calling userLoader.clear() after changing a user. The problem with this is that that userLoader.clear() isn't broadcast to all other instances in your cluster.

**Comment by ThisIsMissEm** [comment] 2017-01-15 19:08
Not just that, but dataloader is really designed for just the single request lifecycle – to handle cases where, say you have a article with comments, that you don't fetch the user details for every single user who's commented, and instead, you just fetch once per unique user.

i.e., because of the documentation, people are using dataloader for things which it was not intended, and hence, getting odd & unintended side-effects

**Comment by migueloller** [comment] 2017-01-24 04:26
@ThisIsMissEm, why would using DataLoader with something like Redis or Memcached go against what DataLoader was intended for? Why not use DataLoader both to batch requests (to avoid the n+1 problem) and also as an application-wide cache using a distribute key-value store?

As long as the business model layer is handling authorization correctly it shouldn't be an issue to share the cache between requests, right?

**Comment by ThisIsMissEm** [comment] 2017-01-24 16:36
Indeed! So, essentially we shouldn't talk of DataLoader as a *cache*, and instead talk of it as a *batcher* for requests to external services (databases, other services, etc).

If you have a piece of code that has a `batch` operator that is cache aware, then sure, use that, but talking of dataloader itself as a cache is confusing

**Comment by leebyron** [comment] 2017-01-30 20:41
Hey @ThisIsMissEm I'd be happy to accept PRs that improved the documentation. Though I'm curious what you would suggest we use instead of "cache".

It's absolutely true that DataLoader does not and should not replace Redis in an architecture. However maybe the confusion is that "cache" is an overloaded term? For instance most would not suggest you can ditch Redis because Browsers have a cache, but also most would not suggest that browser-cache be called something other than a "cache". It seems like the root of the issue is that "cache" can mean a lot of different things based on context. It's really important for the large majority of (appropriate) uses of DataLoader that it caches loads to avoid repeat loads, but improving confusion around appropriate use of DataLoader and it's cache would be awesome. 

I'm open to ideas.

**Comment by leebyron** [comment] 2017-01-30 23:28
I just pushed some initial changes to Readme that hopefully helps make it more clear that Caching behavior should be used in a per-request way.

I'm going to close this issue since we're all in agreement about what needs to be done, though feel free to continue conversation or to keep linking people here who are looking for more information. Any PRs that further improve the language would be really helpful.

**Closed by leebyron** 2017-01-30 23:28 UTC

**Comment by ThisIsMissEm** [comment] 2017-01-31 18:12
@leebyron thanks for the response! I'll try to rework the documentation soon, but it may be a week or two before I get to it.

**Comment by timqian** [comment] 2018-05-28 09:46
@leebyron @ThisIsMissEm @migueloller 
Let alone the implementation, I think the APIs exposed by dataloader is also suitable for application-level cache, this might be the reason which makes people use it that way.
What do your think of [this package](https://github.com/DubFriend/redis-dataloader) that wraps dataloader using redis as the backend, and make the `clear` method a promise. 
I think this lib resolves the problems @migueloller brought out on his comment.
